name: Theme Build and Deploy

on:
    push:
        branches: [
          prod
        ]
    pull_request:
        branches: [
          prod
        ]
        paths-ignore:
            - 'README.md'
            - 'wordpress/**'
jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: build and deploy
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: yarn

        - name: Build
          run: yarn production

        - name: Adding Known Hosts
          run: |
            mkdir -p ~/.ssh/
            ssh-keyscan -H ${{ secrets.SFTP_URL }} >> ~/.ssh/known_hosts

        - name: Install SSH KEY
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ~/.ssh/known_hosts

        - name: Deploy to server with rsync
          run: rsync -avz --exclude 'node_modules' --exclude '.github' --exclude '.gitignore' --exclude '.gitattributes' /. ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_URL }}:/home/dh_kkxxmh/eiren.pandabrand.net/wp-content/themes/eiren-timber-v2
        
        - name: Display status from deploy
          run: echo "{name}={value}" >> $GITHUB_OUTPUT