name: Theme Build and Deploy

on:
    pull_request:
        branches: [
          prod
        ]
        paths-ignore:
            - 'README.md'
            - 'wordpress/**'
jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: build and deploy
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: yarn

        - name: Build
          run: yarn production

        - name: Adding Known Hosts
          run: |
            mkdir -p ~/.ssh/
            ssh-keyscan -H ${{ secrets.PROD_SFTP_URL }} >> ~/.ssh/known_hosts

        - name: Install SSH KEY
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
            known_hosts: 'unneccessary'

        - name: Deploy to server with rsync
          run: rsync -avz --exclude 'node_modules' --exclude '.github' --exclude '.gitignore' --exclude '.gitattributes' ./* ${{ secrets.PROD_SFTP_USER }}@${{ secrets.PROD_SFTP_URL }}:~/eirencaffall.com/wp-content/themes/eiren-timber-v2
        
        - name: Display status from deploy
          run: echo "{name}={value}" >> $GITHUB_OUTPUT
